name: tateyomi_gigarizer
description: Example Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^4.5.0
  url_strategy: ^0.2.0
  validators: ^3.0.0
  cupertino_icons: ^1.0.2
  universal_html: ^2.0.8
  visibility_detector: ^0.2.2
  adaptive_scrollbar: ^2.1.2

  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  flutter_colorpicker: ^1.0.3
  esys_flutter_share_plus: ^2.1.0
  archive: ^3.2.2
  path_provider: ^2.0.9
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
       - asset: fonts/NotoSansJP-Regular.otf  
